# Generated by Django 4.1 on 2022-08-18 08:10

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSession',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator])),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator])),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_authenticated', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.user')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('credential_id', models.TextField(primary_key=True, serialize=False)),
                ('credential_public_key', models.TextField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.user')),
            ],
        ),
    ]
